### ISSUE TITLE
TypeError: dialogflow.SessionsClient is not a constructor on glitch

### ISSUE THREAD

**Issue by prashant7july** [googleapis/nodejs-dialogflow#127] opened 2018-07-07 00:23 UTC
Hi, I have facing the issue as below in https://glitch.com, How to resolve?

```
TypeError: dialogflow.SessionsClient is not a constructor
    at /app/server.js:29:25
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:335:12)
    at next (/rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/rbd/pnpm-volume/da59de95-5f29-48a0-8ac6-325d9ce14734/node_modules/.registry.npmjs.org/serve-static/1.13.2/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
```

**Comment by JustinBeckwith** [comment] 2018-09-21 17:47
Greetings!  Can you share the exact code snippet you're trying to use?  Is this running on the server, or in the browser?

**Comment by AlvarDev** [comment] 2018-10-01 21:59
Hi @prashant7july, did you resolved the issue? 
I resolved it changing the version of the lib version:

from **"dialogflow": "^4.0.3"** to **"dialogflow": "0.6.0"**

source: [](https://www.npmjs.com/package/dialogflow)

let me know if it helps

**Comment by BlueSeph28** [comment] 2020-03-02 18:44
Why this issue is closed? I have the same error with runkit

Code:

```
try {
const event = {
    call_sid: "12345678799",
    speech_result: "Hola",
}
	let projectId = "projectId"

		let privateKey = "privateKey"
		let clientEmail = "clientEmail"
		let config = {
			credentials: {
				private_key: privateKey,
				client_email: clientEmail
			}
		}
	
		let sessionClient = new dialogflow.SessionsClient(config)


		const sessionPath = sessionClient.sessionPath(projectId, event.call_sid);

		const request = {
			session: sessionPath,
			queryInput: {
				text: {
					text: event.speech_result,
					languageCode: LANGUAGE_CODE
				}
			}
		};
		console.log("sirve?");
		console.log(sessionClient.detectIntent(request));
		/*
			sessionClient.detectIntent(request).then(element => {
			    console.log(element);
			   callback(null, element); 
			})
			.catch(err => {
			    console.log(err);
			    callback(err);
			});*/
	}
	catch(err) {
	    console.log(err);
	}
```

**Comment by JustinBeckwith** [comment] 2020-03-02 19:12
This looks to be related to webpack type environments.

**Comment by alexander-fenster** [comment] 2020-03-02 19:42
Hi @BlueSeph28,

What you see might be a RunKit bug. I reproduced it here: https://runkit.com/alexander-fenster/5e5d5d2e21b63e00141512ca#:

![image](https://user-images.githubusercontent.com/4015807/75711006-7b24db80-5c7a-11ea-83e6-2b19e2ad56d8.png)

First, I tried to load another Google Cloud library (`@google-cloud/speech`), and it worked (at least it created a client properly).

Then, for `dialogflow`, weird stuff happens: for some reason, it shows the version as `4.0.3` (which is totally wrong, this package is currently at `1.2.0`). Seems like for whatever reason it actually picks https://www.npmjs.com/package/apiai instead (which is _really_ old).

So, I would advice that you contact RunKit support and figure out why the wrong package gets imported.

Good news! We are planning to publish the next Dialogflow library version as `@google-cloud/dialogflow` (rather than just `dialogflow`), and it will _probably_ fix this weird bug.

**Comment by Mohini0104** [comment] 2020-08-25 19:51
@google-cloud/dialogflow didn't help me in my scenario , whereas only dialogflow worked out in a  better way

**Comment by Mohini0104** [comment] 2020-08-25 19:53
An error message "sessionClient.projectAgentSessionPath is not a function
    at runSample" like this is coming up on my console and i'm trying to resolve it but unable to do so. Please kindly help.

**Comment by sumitsoni516** [comment] 2020-09-27 19:58
> An error message "sessionClient.projectAgentSessionPath is not a function
> at runSample" like this is coming up on my console and i'm trying to resolve it but unable to do so. Please kindly help.

change this "sessionClient.projectAgentSessionPath "  to "sessionClient.sessionPath"  . not Session its session ok.
and also change the directories "\" to "/".

**Comment by sumitsoni516** [comment] 2020-09-27 20:00
> @google-cloud/dialogflow didn't help me in my scenario , whereas only dialogflow worked out in a better way

remove @google-cloud and be it remain  'dialogflow'

**Comment by groverHarshit** [comment] 2020-10-26 09:50
Try removing dialogflow and reinstalling

`npm uninstall dialogflow`

`npm install --save dialogflow`

Mine worked this way

**Comment by telpirion** [comment] 2021-02-22 22:41
It looks like there is a workaround for this issue, so I'm going to close it. Please feel free to re-open this issue with more information.

**Closed by telpirion** 2021-02-22 22:41 UTC
Labels: api: dialogflow, priority: p2, type: process, web

**Comment by eGlobeBizCom** [comment] 2021-07-29 22:21
**Subject: Firebase Functions Dashboard shows this error message: " TypeError: dialogflow.SessionsClient is not a constructor"  in 2021**

Hi All

Our Firebase Functions web apps connected with Dialogflow platform API had worked correctly from 2017 till June/2021;  Then, we updated the following libraries with our code package in July/2021; Then, our input on our web apps cannot be passed to our chatbot on Dialogflow;  We found the above Error Message inside Firebase Functions Dashboard;  We have done the following work to solve this issue, but the above issue cannot be fixed;

* The following line of code in our Index.js had worked before this code package is updated to the latest Firebase Functions libraries released after Jan/ 2021; Now the following code generated the above 
```
============
     // Create a new session
     const sessionClient = new dialogflow.SessionsClient();
     const sessionPath = sessionClient.sessionPath(projectId, sessionId);
==============
```

*This code package is updated with these libraries yesterday and this code package generated the above Error Message:
```
==========
   firebase-tools@9.16.0
    firebase-admin@9.11.0
   + googleapis@82.0.0
+ dialogflow@4.0.3
+ node-fetch@2.6.1
+ @google-cloud/translate@6.2.6
=============
```

*We tried to find the causes and solution for the above error over the web and the related help forums, here are what we found so far:
https://pipedream.com/apps/google-dialogflow
https://github.com/googleapis/nodejs-dialogflow/issues/288
https://github.com/googleapis/nodejs-dialogflow/issues/127
We tried several suggestions in the above posts and none worked.

*Any suggestions and help will be highly appreciated for the above urgent Error Message!!
