### ISSUE TITLE
How to set responses

### ISSUE THREAD

**Issue by Istorn** [googleapis/nodejs-dialogflow#422] opened 2019-09-04 18:26 UTC
Given the Intent interface:

```
export interface Intent {
  name?: string;
  displayName: string;
  webhookState?: string;
  priority?: number;
  isFallback?: boolean;
  mlEnabled?: boolean;
  inputContextNames?: string[];
  events?: string[];
  trainingPhrases?: TrainingPhrase[];
  action?: string;
  outputContexts?: Context[];
  resetContexts?: boolean;
  parameters?: Parameter[];
  messages?: Message[];
  defaultResponsePlatforms?: string[];
  rootFollowupIntentName?: string;
  parentFollowupIntentName?: string;
  followupIntentInfo?: FollowupIntentInfo[];
}
```
I supposed that "messages" is the right paramters where to set responses of my intent.

What I've done:

```
 messageText.text= [messageToBuild];
          messageText.message="text";
          messagesBuilt.push(messageText);
```
After I got messages, I put them in my intent.

```
const intent = {
      displayName: displayName,
      trainingPhrases: trainingPhrasesBOT,
      messages: messagesBuilt,
      //parameters:parameterBOT,
     
    };
```

Once I create the intent itself, there won't be any responses set on Dialogflow, while it should be "Ciao $nome benvenuto!"

I supposed that the intent's parameter named "nome" wasn't set, but it is.

How to figure it out?

**Comment by Istorn** [comment] 2019-10-04 08:42
Is there anyone could help me?!

**Comment by nnegrey** [comment] 2019-10-04 17:45
This looks like a duplicate of https://github.com/googleapis/nodejs-dialogflow/issues/416, if not, please feel free to re-open.

**Closed by nnegrey** 2019-10-04 17:45 UTC
Labels: help wanted, type: question
