### ISSUE TITLE
README as wrong install instructions

### ISSUE THREAD

**Issue by Mouser13** [googleapis/nodejs-dialogflow#720] opened 2020-11-25 17:41 UTC
Thanks for stopping by to let us know something could be better!

1) Is this a client library issue or a product issue?
This is the client library for dialogflow says npm install dialogflow when should be updated to npm install @google-cloud/dialogflow. Minor issue but me and cowork lost few hours to this.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-dialogflow/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
no 

#### Steps to reproduce

  1.  npm install dialogflow
  2. npm run test 
  3. production module not found for @google-cloud/dialogflow

Readme as wrong steps should be npm install @google-cloud/dialogflow

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by laljikanjareeya** [comment] 2020-11-30 05:41
@Mouser13 Thanks for the report. Closing this issue as it's duplicate of #677. we will fix it soon.

**Closed by laljikanjareeya** 2020-11-30 05:41 UTC
Labels: api: dialogflow, triage me
