### ISSUE TITLE
Parameter bug with createIntent method

### ISSUE THREAD

**Issue by rnsloanwool** [googleapis/nodejs-dialogflow#898] opened 2021-11-10 04:18 UTC
#### Environment details

  - OS: OS X 11.6
  - Node.js version: v12.18.3
  - npm version: 6.14.6
  - `@google-cloud/dialogflow` version: 3.3.0

#### Steps to reproduce

1. create an intent using `createIntent`. It should have at least one entity usage in its training phrases. It should not have any parameters
2. inspect the intent after creation with `getIntent()`. It should not have any parameters
3. check the Intent in the Dialogflow UI. The intent should _appear_ to have a parameter that was automatically generated. But it does not actually exist as confirmed by the `getIntent()` response. Saving the intent using the UI will create the parameter

![parameter](https://user-images.githubusercontent.com/61669793/141047247-1dfb6c51-eef4-422a-9afa-ab98eaabb0b1.png)

Code example:

```
const dialogflow = require('@google-cloud/dialogflow');

process.env.GOOGLE_APPLICATION_CREDENTIALS = 'credentials.json';

const GCP_PROJECT = 'xxxx';
const intentsClient = new dialogflow.IntentsClient();

async function main() {
  const agentPath = intentsClient.agentPath(GCP_PROJECT);
  const createIntentRequest = {
    parent: agentPath,
    intent: {
      displayName: 'intent-parameter-check',
      trainingPhrases: [
        {
          parts: [
            {
              text: 'my email address is '
            },
            {
              text: 'example@example.com',
              entityType: '@sys.email',
              alias: 'sys-email'
            }
          ],
          type: 'EXAMPLE'
        }
      ],
      messages: [
        {
          platform: 'PLATFORM_UNSPECIFIED',
          text: {
            text: ['hello world']
          }
        }
      ]
    }
  };

  const [response] = await intentsClient.createIntent(createIntentRequest);
  const [intent] = await intentsClient.getIntent({
    name: response.name,
    intentView: 'INTENT_VIEW_FULL'
  });
  
  console.dir(intent, { depth: null });
  // no parameter exists for intent:
  /*
  {
    inputContextNames: [],
    events: [],
    trainingPhrases: [
    {
      parts: [
        {
          text: 'my email address is ',
          entityType: '',
          alias: '',
          userDefined: false
        },
        {
          text: 'example@example.com',
          entityType: '@sys.email',
          alias: 'sys-email',
          userDefined: false
        }
      ],
      name: 'b9d17106-4825-414f-8f16-eb3d00753970',
      type: 'EXAMPLE',
      timesAddedCount: 0
    }
  ],
    outputContexts: [],
    parameters: [],
    messages: [
    {
      platform: 'PLATFORM_UNSPECIFIED',
      text: { text: [ 'hello world' ] },
      message: 'text'
    }
  ],
    defaultResponsePlatforms: [],
    followupIntentInfo: [],
    name: 'xxxx',
    displayName: 'intent-parameter-check',
    priority: 500000,
    isFallback: false,
    webhookState: 'WEBHOOK_STATE_UNSPECIFIED',
    action: '',
    resetContexts: false,
    rootFollowupIntentName: '',
    parentFollowupIntentName: '',
    mlDisabled: false
  }
   */
}

main();
```

----

This looks to be a product issue, however the Dialogflow CX API prevents this same problem from occurring as it rejects the creation of a similar intent if it does not include the required parameters.

**Comment by galz10** [comment] 2021-11-15 19:33
Hi @rnsloanwool, i'm having a tough time understanding what you're trying to achieve. Are you trying to create an intent with an email and make sure the email isn't a parameter ?

**Comment by rnsloanwool** [comment] 2021-11-15 23:17
Hi @galz10 . No email was just a random entity used as an example. 

If would like to know the actual use case that made us discover this, we are creating Intents via the API that use a custom entity in its training phrases. The Intents have the webhook enabled and in the fulfilment layer the parameter value is used to generate the response. However, we noticed that no parameter value existed.

Investigating, we discovered that while the Dialogflow UI shows a parameter being automatically generated due to the presence of an entity in the training phrases, it actually does not exist. It needs to be explicitly created as part of the  `createIntent` call.

For CX, if you create an Intent via the API that includes an entity in its training phrase and do not explicitly create the parameter as part of the same request, the API will reject the request.

**Comment by galz10** [comment] 2021-11-15 23:33
oh okay i see, so let me just restate what you're saying so i make sure we're on the same page. So basically when calling the API without a parameter value the create intent call should be rejected correct ? 

when looking at your code it looks like you are specifying the parameter here : 

```
          {
              text: 'example@example.com',
              entityType: '@sys.email',
              alias: 'sys-email'
            }
```
That's why when you look at the UI the parameter shows up.

**Comment by rnsloanwool** [comment] 2021-11-15 23:47
> That's why when you look at the UI the parameter shows up.

A parameter shows up in the UI, but if you check the intent afterwards with a call to `getIntent()` or try to use the parameter value in a fulfilment layer, it does not exist.

My expected behaviour:

1. reject the API call unless you explicitly create the parameter in the same request, the CX solution, e.g. 
```
parameters: [
        {
          displayName: 'sys-email',
          entityTypeDisplayName: '@sys.email',
          value: '$sys-email',
          isList: false
        }]
```

must be present.

2. automatically create the parameter.

**Comment by galz10** [comment] 2021-11-16 19:20
@rnsloanwool okay i understand now, i was able to reproduce what you are seeing and i created a bug. 
Thank you for bringing this to our attention. I'll probably close this bug soon but if theres anything new feel free to reopen it.

**Closed** 2021-11-23 20:37 UTC
Labels: priority: p2, type: bug, api: dialogflow
