### ISSUE TITLE
Add support for angular

### ISSUE THREAD

**Issue by ceciliazcx** [googleapis/nodejs-dialogflow#390] opened 2019-07-23 08:05 UTC
Error message
```
ERROR in ./node_modules/google-gax/build/src/operationsClient.js
Module not found: Error: Can't resolve './operations_client_config' in 'C:\Users\chenxi.zhao\workspace\chatbot-designer\node_modules\google-gax\build\src'
ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\chenxi.zhao\workspace\chatbot-designer\node_modules\google-auth-library\build\src\auth'
```

#### Environment details

  - OS: WIN 10
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `dialogflow` version:0.10.2

#### Steps to reproduce
I am very sure the library `google-gax` and `google-auth-library` is correct installed.
But I got error as above.
Basically, this is angular8 + universal project.  
when I build project with ` npm run build:ssr`, it says the modules not found.
I google a lot, it says google library compact with webpack? I tried everything, but nothing works.

  ```import { Injectable } from '@angular/core';
import {Observable} from "rxjs";

import { Intent } from 'src/app/models/intent';

const dialogflow = require('dialogflow');

@Injectable({
  providedIn: 'root'
})
export class IntentService {
  .......
  .......
  readonly intentsClient = new dialogflow.IntentsClient(this.opts);
  readonly request = {
      parent: this.projectAgentPath,
      intentView: 'INTENT_VIEW_FULL',
  };

  constructor() { }

  fetchIntents(): Observable<Intent[]> {
    return this.intentsClient.listIntents(this.request);
  }
}
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment] 2019-07-23 18:21
👋 hello @ceciliazcx, currently `nodejs-dialogflow` does not work in a frontend context, as it relies on libraries that exist in Node.js but not the browser, e.g., `http2`, `child_process`.

there are efforts in the works to make libraries like dialogflow work for the frontend, but we're not quite there yet.

**Comment by ceciliazcx** [comment] 2019-07-23 23:34
@bcoe ok. Thx for reply. I basically only want to get intents from dialog flow. Is there any other I can do it from angular?

**Comment by JustinBeckwith** [comment] 2019-07-23 23:37
Could you give this library a try?
https://github.com/googleapis/google-api-nodejs-client/

It's less easy to work with, but is known to be webpack-able.

**Comment by callmehiphop** [comment] 2019-07-31 21:11
Going to close this as a duplicate of https://github.com/googleapis/google-cloud-node/issues/2933

**Closed by callmehiphop** 2019-07-31 21:11 UTC
Labels: frontend, type: feature request

**Comment by frederickjjoubert** [comment] 2021-06-24 15:42
Hey guys, is angular still not supported? I am trying to add dialog flow to my ionic angular project and got the same error.
