### ISSUE TITLE
Error: 3 INVALID_ARGUMENT: Read only field 'followup_intent_info' cannot be updated.

### ISSUE THREAD

**Issue by omfd** [googleapis/nodejs-dialogflow#114] opened 2018-06-25 08:19 UTC
If you updating an intent which has a follow up intent/intents using the nodejs clients - you will land up with this error. 
#### Environment details

  - OS: Linux
  - Node.js version: LTS (8.11)
  - npm version: (6)
  - `dialogflow` version: (latest)

#### Steps to reproduce

  1. Add training example to an intent which has followup intent

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jrash06** [comment] 2018-06-26 20:15
Have you tried the update mask to mask out updates to followup intent?
https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/10dc26914c09e70fd07f7ccaa818e9076f5de25b/protos/google/cloud/dialogflow/v2beta1/intent.proto#L748

**Comment by edge0701** [comment] 2018-11-09 10:20
Have confirmed this myself and have submitted a bug report from inside Dialogflow console itself. I suggest that others running into this issue do the same to increase it's visibility.

**Comment by sgazzillo3DBB** [comment] 2018-11-14 16:00
We are having the same issue.  What is the bug report id?

**Comment by edge0701** [comment] 2018-11-14 16:27
I got this response from the DF support team and I have tested it working. Been meaning to update this thread. Good luck!

> Hi,
> 
> Thanks for reaching out to Dialogflow Support.
> 
> Our engineers are working to fix this issue. At this time, a workaround is to specify root_followup_intent_name in updateMask (and don't pass a value for root_followup_intent_name).
> 
> 
> Regards,
> 
> Ace
> Dialogflow Support Team

**Comment by 3DBB** [comment] 2018-11-14 16:37
Excellent. Thank you for the quick response!

**Comment by petmat** [comment] 2019-03-01 08:46
Is there an update to this issue?

**Comment by TimothePearce** [comment] 2019-03-10 12:44
Just to clarify [`updateMask`](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.UpdateIntentRequest) attribute is a [`FieldMask`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.FieldMask).

This is an example of how to use it in order to fix the issue:
```js

const intentsClient = new dialogflow.IntentsClient({
  credentials: {
    client_email,
    private_key,
  }
});

intentsClient.updateIntent({
  intent,
  updateMask: {
    paths: ['rootFollowupIntentName'],
  },
});
```

**Comment by Mag90** [comment] 2019-03-20 15:01
Its seams like updating the intent displayName doesnt work when using the updateMask..

**Comment by bcoe** [comment] 2019-04-03 20:16
@omfd are you still running into issues on the latest release of the library?

**Comment by callmehiphop** [comment] 2019-06-03 20:44
Looks like @Mag90's code should be the fix here. I'm going to close this issue out, but please let me know if you think that is a mistake and I'll happily re-open 😎

**Closed** 2019-06-03 20:45 UTC
Labels: needs more info, type: question

**Comment by Gevert92** [comment] 2019-11-28 21:15
Good my people, I know this post has some time but I would like to ask if any of you have created followup with this DialogFlow API, I'm looking for a way to do it.

I think I tried it with the code:
let intent = {
        displayName: dataIntent.nameIntent,
        trainingPhrases: trainingPhrases,
        messages: message
    };
    
let response = await IntentsClient.createIntent( {parent:parent, intent:intent} );

But I can't find a way to create the followup, please help.
