### ISSUE TITLE
newline in response not appearing

### ISSUE THREAD

**Issue by KlausGathmann** [googleapis/nodejs-dialogflow#235] opened 2018-12-04 09:28 UTC
Hello,

I have a small issue and I do not know if it is expected behaviour. When I call the API the newline characters in the text responses are disappearing. Is this normal behaviour? Is there a configuration to change that?

Thank you

**Comment by nnegrey** [comment] 2018-12-19 19:08
Hi, looking to see if this is a bug or intended behavior.

**Comment by callmehiphop** [comment] 2019-06-03 19:03
@nnegrey any updates here?

**Comment by callmehiphop** [comment] 2019-06-05 19:47
Hasn't been a whole lot of activity here lately, so I'm going to close this out. If anyone continues to experience this, you can either let us know or try opening an issue over at https://cloud.google.com/support/docs/issue-trackers.

**Closed by callmehiphop** 2019-06-05 19:47 UTC
Labels: backend, type: question
