### ISSUE TITLE
AgentsClient timeout

### ISSUE THREAD

**Issue by alexmontesg** [googleapis/nodejs-dialogflow#381] opened 2019-07-08 18:26 UTC
I'm probably doing something wrong, but I just cannot see it. I'm trying to export and restore agents using the AgentsClient. Once I do the request, my code just hangs on the await until it times out. From the dialogflow console I can see that the agent was actually restored, I just seem to receive no response from the API.

### Environment details
OS: Mac OS Mojave (10.14.5)
Node.js: v10.12.0
`dialogflow`: 0.9.1
### Code extract
```javascript
  const df = require('dialogflow')
// ...
  async _restoreAgent (credentials, agentName) {
    const fileContent = JSON.parse(fs.readFileSync(credentials, 'utf8'));
    const projectId = fileContent.project_id;
    const agentsClient = new df.AgentsClient({
      keyFilename: credentials,
      projectId
    });
    const agentContent = new Buffer(fs.readFileSync(agentName)).toString('base64');
    const request = {
      parent: `projects/${projectId}`,
      agentContent
    };
    const promise = agentsClient.restoreAgent(request);
    console.log(promise); // Prints: Promise { <pending>, cancel: [Function] }
    const result = await promise;
    console.log(result); // Never gets here, but agent actually restored
  }
```

I tried using the `then()` `catch()` syntax, as I saw it on the unit tests, but I get the same result. I also have the same issue trying to do an `exportClient`.

**Comment by callmehiphop** [comment] 2019-11-15 15:17
@alexmontesg forgive me for the necrobump, but did you ever manage to resolve this issue?

**Comment by callmehiphop** [comment] 2019-11-21 08:03
Going to close this since it looks to be a duplicate of #450

**Closed by callmehiphop** 2019-11-21 08:03 UTC
Labels: priority: p2, type: bug
