### ISSUE TITLE
Connecting to Dialogflow using ReactJS keeps giving Authentication errors.

### ISSUE THREAD

**Issue by YunusGogce** [googleapis/nodejs-dialogflow#463] opened 2019-11-13 14:33 UTC
I'm trying to connect to Dialogflow using ReactJS. I've tried the sample code as below:

```
const dialogflow = require('dialogflow');

async function runSample(projectId = '[my-project-id]') {
  // A unique identifier for the given session
  const sessionId = '123456789';

  // Create a new session
  const sessionClient = new dialogflow.SessionsClient({
    keyFilename: "./[file-name-with-credentials].json"
  });
  const sessionPath = sessionClient.sessionPath(projectId, sessionId);

  // The text query request.
  const request = {
    session: sessionPath,
    queryInput: {
      text: {
        // The query to send to the dialogflow agent
        text: 'Hello',
        // The language used by the client (en-US)
        languageCode: 'en-US',
      },
    },
  };

  // Send request and log result
  const responses = await sessionClient.detectIntent(request);
  console.log('Detected intent');
  const result = responses[0].queryResult;
  console.log(`  Query: ${result.queryText}`);
  console.log(`  Response: ${result.fulfillmentText}`);
  if (result.intent) {
    console.log(`  Intent: ${result.intent.displayName}`);
  } else {
    console.log(`  No intent matched.`);
  }
}
```

It gives me this error: You need to pass auth instance to use gRPC-fallback client in browser. Use OAuth2Client from google-auth-library.

I have set up the GOOGLE_APPLICATION_CREDENTIALS environment variable too. Is there any simple way to make the connection? Can someone share an example. Maybe using Ajax call? Thank you.

**Comment by callmehiphop** [comment] 2019-11-13 19:57
@YunusGogce could you tell us a little more about your application - are you trying to run this in the browser/electron/etc.?

**Comment by YunusGogce** [comment] 2019-11-13 20:02
@callmehiphop I'm trying to run in in the browser using React.

**Comment by callmehiphop** [comment] 2019-11-13 20:14
@YunusGogce I'm going to refer you to https://github.com/googleapis/nodejs-dialogflow/issues/405#issuecomment-529713296, since I believe this is just a duplicate of that issue.

Let us know if that example helps!

**Closed by callmehiphop** 2019-11-13 20:14 UTC
Labels: needs more info, type: question

**Comment by YunusGogce** [comment] 2019-11-13 20:31
@callmehiphop I actually tried using OAuth2Client. As far as I understand it uses the users Google account to get a token. I don't want this. I want users to be able to chat with the dialogflow chatbot without having to login.

Please correct me if my understanding is wrong.

**Comment by callmehiphop** [comment] 2019-11-13 20:53
@YunusGogce AFAIK that is the only way to use this client in a browser. You might consider using the https://github.com/googleapis/google-api-nodejs-client module instead.
