### ISSUE TITLE
gRPC has issues when used in conjunction with Electron to make a PC app (keeps happening)

### ISSUE THREAD

**Issue by ottogutierrez** [googleapis/nodejs-dialogflow#302] opened 2019-03-15 13:36 UTC
Hello,

I keep having the same issue as [this one](https://github.com/googleapis/nodejs-dialogflow/issues/211). It my solution worked for a while, but when I updated Electron it stopped working. I tried to rebuild the grpc again with the different target so many times (deleting the node_modules, and package-lock.json) but nothing is working I keep getting the same error:
`App threw an error during load
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.1-win32-x64-unknown
Found: [electron-v3.0-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system`

**Comment by callmehiphop** [comment] 2019-03-15 16:55
Sounds like it might be a duplicate of https://github.com/grpc/grpc-node/issues/780

**Comment by bcoe** [comment] 2019-04-03 20:25
@ottogutierrez I noticed that grpc/grpc-node#780 was closed, are you continuing to bump into issues? (wondering if the resolution in `#780` did the trick for you)

**Comment by ottogutierrez** [comment] 2019-04-03 20:44
@bcoe No, I wasn’t able to fix it. The only way that worked is to go back to the last functioning version of the software, using the package-lock.json that luckily I had on a previous commit of my project. I guess the gRPC is still working on a fix for this

**Comment by callmehiphop** [comment] 2019-06-05 19:54
We've seen similar reports in other clients, however one user has reported that the following command worked for them

```
$ npm install grpc --runtime=electron --target=5.0.2
```

Since this isn't a client issue, I'm going to close this out. If you continue to run into this issue and the posted workaround does not help, I would suggest opening an issue over at [grpc](https://github.com/grpc/grpc-node)

**Closed by callmehiphop** 2019-06-05 19:54 UTC
Labels: priority: p2, status: duplicate, type: bug
