### ISSUE TITLE
Permission denied : IAM permission

### ISSUE THREAD

**Issue by florian02100** [googleapis/nodejs-dialogflow#151] opened 2018-08-23 16:04 UTC
Hi, I've problem with dialogflow . 

```
'IAM permission \'dialogflow.sessions.detectIntent\' on \'projects/alanaconding/agent\' denied.' }
```

But i export credentials with JSON file.

my code :

```js
let express = require('express')
let app = express()
let bodyParser = require('body-parser')
const dialogflow = require('dialogflow');
//DialogFlow vairable
const common = require('@google-cloud/common');
const fs = require('fs');
const structjson = require('./structjson.js');
const pump = require('pump');
const through2 = require('through2');
const projectId = 'alanaconding'; //https://dialogflow.com/docs/agents#settings
const sessionId = ' ';
var query = '';
const languageCode = 'fr-FR';

//---------------------
//Moteur de template 
//---------------------
app.set('view engine', 'ejs')

//---------------------
//MIDDLEWARE
//---------------------
//Gestion des fichiers statique
app.use('/assets',express.static('public'))

//Gestion du parsing des messages
app.use(bodyParser.urlencoded({ extended:false}))
app.use(bodyParser.json())

//Gestion des session
/*app.use(session({
  secret: 'azerty',
  resave: false,
  saveUninitialized: true,
  cookie: { secure: false }
}))
// Gestion des messages flash
// Middleware maison 
app.use(require ('./middleware/flash'))*/

function dialogFlowRequest(){

	// You can find your project ID in your Dialogflow agent settings
const projectId = 'alanaconding'; //https://dialogflow.com/docs/agents#settings
const sessionId = ' ';
const query = 'bonjour';
const languageCode = 'fr-FR';

// Instantiate a DialogFlow client.
const dialogflow = require('dialogflow');
const sessionClient = new dialogflow.SessionsClient();

// Define session path
const sessionPath = sessionClient.sessionPath(projectId, sessionId);

// The text query request.
const request = {
  session: sessionPath,
  queryInput: {
    text: {
      text: query,
      languageCode: languageCode,
    },
  },
};

// Send request and log result
sessionClient
  .detectIntent(request)
  .then(responses => {
    console.log('Detected intent');
    const result = responses[0].queryResult;
    console.log(`  Query: ${result.queryText}`);
    console.log(`  Response: ${result.fulfillmentText}`);
    if (result.intent) {
      console.log(`  Intent: ${result.intent.displayName}`);
    } else {
      console.log(`  No intent matched.`);
    }
  })
  .catch(err => {
    console.error('ERROR:', err);
  });
}


//Routes 
app.get('/',(request,response) => {

	response.render('pages/index')

})
app.post('/', (request,response) => {

	if(request.body.message === undefined || request.body.message === ''){
		//request.flash('error',"vous n'avez pas posté de message")
		response.redirect('/')
	} else {
		console.log('envoi requête ');
			dialogFlowRequest();

			}
	})


app.listen(8060);
```

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 10.8.0
  - npm version: 6.2.0
  - `dialogflow` version: 2

Following these steps will guarantee the quickest resolution possible. Thanks!

**Comment by faisalahmedansari20** [comment] 2018-09-06 10:01
make sure you have given admin access to google-service.json which you have set in you system variable GOOGLE APPLICATION CREDENTIAL

**Comment by danilazhar** [comment] 2018-09-18 06:58
> make sure you have given admin access to google-service.json which you have set in you system variable GOOGLE APPLICATION CREDENTIAL

I have given "Project owner" role and I still get an authentication error.

**Comment by dysnomia** [comment] 2018-09-19 01:55
Could you please double-check what JSON file `GOOGLE_APPLICATION_CREDENTIALS` points set:

```
console.log(process.env.GOOGLE_APPLICATION_CREDENTIALS);
```

And then look at the client_email field in the file to make sure you granted the IAM permissions to exactly the right account.

**Comment by beccasaurus** [comment] 2019-01-31 01:31
@nnegrey @matthewayne Do y'all have any particular context for this?

I haven't personally run into this when using Dialogflow. The steps I've taken have simple been enabling the Dialogflow API. Reading the steps to reproduce above, it's not clear to me how to reproduce this.

I'm curious is this is something Dialogflow users run into or if it's common to all Google Cloud APIs.

**Comment by nnegrey** [comment] 2019-01-31 17:35
From most issues I've seen, it's usually from what `dysnomia` said about setting the GOOGLE_APPLICATION_CREDENTIALS:

```
export GOOGLE_APPLICATION_CREDENTIALS=keyfile.json
```

But, if it is not that, then I'd need some more info.

**Comment by nnegrey** [comment] 2019-01-31 17:36
To further follow up, the README has a [Before you begin section](https://github.com/googleapis/nodejs-dialogflow/tree/master/samples#before-you-begin)

Which takes you [here](https://github.com/googleapis/nodejs-dialogflow/blob/master/README.md#before-you-begin)

[Step 4](https://github.com/googleapis/nodejs-dialogflow/blob/master/README.md#using-the-client-library) in that doc is to setup auth

**Comment by beccasaurus** [comment] 2019-02-01 23:48
If there is a reproduction of this which is not solved by setting `GOOGLE_APPLICATION_CREDENTIALS=[path to service account key.json]`, please feel free to enter a reproduction case and we can re-open!

Pending more information, **closing** as we have `GOOGLE_APPLICATION_CREDENTIALS` documented in various locations, including near the top of most of our product Quickstart pages. For Dialogflow EE, the Quickstart begins with [Set up your GCP project and authentication](https://cloud.google.com/dialogflow-enterprise/docs/quickstart-api#set-up-your-gcp-project-and-authentication), including the top of this repo's [README](https://github.com/googleapis/nodejs-dialogflow#using-the-client-library).

**Closed by beccasaurus** 2019-02-01 23:48 UTC
Labels: type: question

**Comment by codingWithMittens** [comment] 2019-05-21 19:16
In my case this was because my Service Account was a "DialogFlow API Client" instead of a "DialogFlow API Admin". Apparently the Export function requires admin.

**Comment by pranjalvatsa** [comment] 2021-06-07 11:53
Hi,

I have followed all of these steps but still getting PERMISSION DENIED. My service account is set to DialogFlow Admin.

**Comment by matheusbaumgart** [comment] 2021-09-02 03:52
For me, the issue was that months ago I've added GOOGLE_APPLICATION_CREDENTIALS to my `.zshrc` file. Now while working on another project the `.env` sets GOOGLE_APPLICATION_CREDENTIALS to another path but gets ignored and the one from my system variable is used instead.
