### ISSUE TITLE
Using a root ca file for api calls

### ISSUE THREAD

**Issue by aybhalala** [googleapis/nodejs-dialogflow#287] opened 2019-02-23 20:58 UTC
I am using this library for an application. When I am behind a proxy and make API calls, I get an SSL verify error. I tried storing the root ca cert file in env variable NODE_EXTRA_CA_CERTS but this does not seem to resolve the issue. When I use the same project without proxy or extra ca cert file everything runs fine. But I need to use this behind a proxy. In grpc I see that we can specify such file using the createSSL method. Is there any clean solution to do that in this library.

**Comment by callmehiphop** [comment] 2019-02-25 10:16
I'm going to close this because it looks like a duplicate of #20, if thats not the case let us know.

**Closed by callmehiphop** 2019-02-25 10:16 UTC
Labels: triage me
