### ISSUE TITLE
queryResult.intent.inputContextNames array is always empty

### ISSUE THREAD

**Issue by Isaben** [googleapis/nodejs-dialogflow#646] opened 2020-07-15 04:43 UTC
#### Environment details

  - OS: Windows 10
  - Node.js version: 12.14.1
  - npm version: 6.13.4
  - `@google-cloud/dialogflow` version: 1.2.0

#### Steps to reproduce

Here's the code and an agent zip to reproduce the bug: https://github.com/Isaben/df_issue

The agent `Default Welcome Intent` has `welcome_context` as its output context with lifespan of 1, and a `Second Intent` with the same context as its input. 

Running the aforementioned code, `results2` is correctly matched to `Second Intent`, but its `queryResult.intent.inputContextNames` array is empty, which is obviously incorrect, as shown in the picture below:
![image](https://user-images.githubusercontent.com/20483141/87503725-520a5380-c63b-11ea-9561-bd78c354153b.png)

Is this supposed to be the expected behavior and the array should only contain contexts that were directly passed via the `queryParams` object when calling `detectIntent`, or is this indeed a bug?

Thanks.

**Comment by munkhuushmgl** [comment] 2020-08-12 22:47
@Isaben Looks like there is no `package.json` file in your reproduce repo.

Sorry about the late response.

**Comment by Isaben** [comment] 2020-08-20 22:49
@munkhuushmgl yeah sorry about that, I missed it somehow, repo updated. 
Also I tried with the more recent version `3.2.0` and the issue persists.

**Comment by munkhuushmgl** [comment] 2020-08-20 23:48
@Isaben I will try to reproduce it again.

**Comment by munkhuushmgl** [comment] 2021-03-02 20:07
@Isaben 
![image](https://user-images.githubusercontent.com/45373284/109708003-affa9580-7b4f-11eb-949b-033ea4e1fc8d.png)
Not sure if you still having issue or not.

Looks like I got same empty response.

**Comment by munkhuushmgl** [comment] 2021-03-02 20:19
![image](https://user-images.githubusercontent.com/45373284/109709333-35cb1080-7b51-11eb-9350-7f2e57ef4e4d.png)

looks like it working as intended

I do not fully understand what you are trying to accomplish

**Comment by b-loved-dreamer** [comment] 2021-03-25 15:34
This is normal under current API set-up. Closing this issue. Please reopen if needed.

**Closed by b-loved-dreamer** 2021-03-25 15:34 UTC
Labels: api: dialogflow, type: question
