### ISSUE TITLE
Passing Parameters to Contexts

### ISSUE THREAD

**Issue by arielschvartz** [googleapis/nodejs-dialogflow#402] opened 2019-08-10 14:10 UTC
When passing parameters to a new contexts (via createContext or detectIntent), you cannot just passa an object.

For example:
``` 
contextsClient.createContext({
  parent: sessionPath,
  context: {
    name: "projects/my-project-id/agent/sessions/my-session-id/contexts/my-context-name",
    lifespanCount: 1,
    parameters: {
      foo: "bar"
    }
  }
})
``` 

In the above example, the foo parameter is not set in the context. For it to work you should pass like:
``` 
contextsClient.createContext({
  parent: sessionPath,
  context: {
    name: "projects/my-project-id/agent/sessions/my-session-id/contexts/my-context-name",
    lifespanCount: 1,
    parameters: {
      fields: {
        foo: {
          stringValue: "bar"
        }
      }
    }
  }
})
``` 
As solution, I think the better way would be for the lib to handle that and convert. The other way of resolving this problem would be simply updating the documentation.

By the way, I didn't find anywhere in the Dialogflow documentation the possible values for a field (like stringValue). Is there something like numberValue, datetimeValue?

Hope it help other people! =)

**Comment by arielschvartz** [comment] 2019-08-10 14:53
Just discovered that exactly the same applies to passing parameters to the payload of the detectIntent.

**Comment by callmehiphop** [comment] 2019-09-04 16:11
👋 @arielschvartz this looks like a duplicate of https://github.com/googleapis/nodejs-dialogflow/issues/97, which is a fairly common complaint we get here. The client itself is actually generated, so I think getting a feature like this in will be tricky and probably take some time (although I do believe it is on our radar).

In the mean time we've been suggesting using [pb-util](https://www.npmjs.com/package/pb-util) to  convert protobuf structures like this.

**Closed by callmehiphop** 2019-09-04 16:11 UTC
Labels: status: duplicate, type: feature request

**Comment by arielschvartz** [comment] 2019-09-04 16:47
Thank you very much @callmehiphop ! Gonna use the lib for now!

But I suggest adding it to the docs in the dialogflow website! Would be simples and help a lot of people!

**Comment by callmehiphop** [comment] 2019-09-04 17:02
@arielschvartz thanks for the suggestion!

@bcoe any idea how we can do a better job of documenting this? Seems like a common point of frustration for users here, but I'm not really sure how to solve the issue since everything for Dialogflow is generated.

**Comment by vchopDev** [comment] 2019-10-22 10:29
@arielschvartz Thanks a lot man!!!
