### ISSUE TITLE
Unable to connect dialogflow with spreadsheet api

### ISSUE THREAD

**Issue by sanchit892** [googleapis/nodejs-dialogflow#503] opened 2020-01-13 17:16 UTC
I am new to dialogflow and I also have not much knowledge about node.js, I am trying to connect my spreadsheet with dialogflow but unable to do that. Code deploy's without any error on Dialogflow.

Here is code for index.js that i am using 

```js
'use strict';
const functions = require('firebase-functions');
const {WebhookClient} = require('dialogflow-fulfillment');
const {Card, Suggestion} = require('dialogflow-fulfillment');
const axios = require('axios');

 
process.env.DEBUG = 'dialogflow:debug'; //enables lib debugging statements
 
exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
  const agent = new WebhookClient({ request, response });
  console.log('Dialogflow Request headers: ' + JSON.stringify(request.headers));
  console.log('Dialogflow Request body: ' + JSON.stringify(request.body));
 
  function getSpreadsheetData(){
  	return axios.get('https://sheetdb.io/api/v1/atn718vr2x4s7');
  }
  
  function welcome(agent) {
    const name = agent.parameters.name;
    return getSpreadsheetData().then(res => {
    	res.data.map(person => {
            if(person.Name === name)
        	agent.add(`Here are the details for ${name}. Age: ${person.Age}, Email: ${person.Email}, Phone: ${person.Phone}`);
        });
    });
  }
 
  function fallback(agent) {
    agent.add(`I didn't understand`);
    agent.add(`I'm sorry, can you try again?`);
  }


  // Run the proper function handler based on the matched Dialogflow intent name
  let intentMap = new Map();
  intentMap.set('Default Welcome Intent', welcome);
  intentMap.set('Default Fallback Intent', fallback);
  // intentMap.set('saveData', saveDataHandler);
  //intentMap.set('sendEmail', sendEmailHandler);
  agent.handleRequest(intentMap);
});
``

**Comment by vishald123** [comment] 2020-01-22 10:45
Hi @sanchit892, I think using **axios**  for getting spreadsheet data is where the issue is. I did the following way by using **Spreadsheet API** and it did work for me. 

```js
const functions = require('firebase-functions');
const { WebhookClient } = require('dialogflow-fulfillment');
const { google } = require('googleapis');
const sheets = google.sheets('v4');

const SCOPES = ['https://www.googleapis.com/auth/spreadsheets'];
const spreadsheetId = '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms';

process.env.DEBUG = 'dialogflow:debug';

exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
    const agent = new WebhookClient({ request, response });
    console.log('Dialogflow request headers: ' + JSON.stringify(request.headers));
    console.log('Dialogflow request body: ' + JSON.stringify(request.body));

    function getAuthToken(spreadsheetId, sheetName) {
        const auth = new google.auth.GoogleAuth({
            scopes: SCOPES
        });

        return auth.getClient().then((authToken) => {
            const res = sheets.spreadsheets.values.get({
                spreadsheetId: spreadsheetId,
                auth: authToken,
                range: sheetName
            });
            return res;
        });
    }

    function GetNames() {
        const name = agent.parameters.name;
        return getAuthToken(spreadsheetId, sheetName = 'Class Data').then((res) => {
            res.data.values.map(person => {
                agent.add(person[0]);
            });
        }).catch((err) => {
            console.log(err);
        });
    }

    function fallback(agent) {
        agent.add(`I didn't understand`);
        agent.add(`I'm sorry, can you try again?`);
    }

    function welcome(agent) {
        agent.add(`hello hi`);
    }

    let intentMap = new Map();
    intentMap.set(`GetNames`, GetNames);
    intentMap.set(`Default Fallback Intent`, fallback);
    intentMap.set(`Default Welcome Intent`, welcome);

    agent.handleRequest(intentMap);
});

```

Please try and let me know if it works for you.

**Comment by sanchit892** [comment] 2020-01-22 17:20
Thanks @vishald123 for the reply I definitely try that and let you know !!!

**Comment by vishald123** [comment] 2020-02-28 10:57
Hey @sanchit892, any updates? did the solution will work for you?

**Comment by sanchit892** [comment] 2020-02-28 15:38
hey @vishald123, I use the spreadsheets api its working with it, but there is no issue with axios, the issue is with the code and also with the firebase connection. but Now its working fine.

Thanks

**Comment by vishald123** [comment] 2020-03-02 10:13
@sanchit892, Glad that worked. I am closing the issue. Please feel free to reopen the issue if you face the issue again.

**Closed by vishald123** 2020-03-02 10:13 UTC
Labels: api: dialogflow, type: question

**Comment by jjoshua1995** [comment] 2020-03-10 23:15
@sanchit892 
How did you solve the error with axios.
I am facing the same.

**Comment by jjoshua1995** [comment] 2020-03-11 00:27
@vishald123 
I tried using Spreadsheet API but still i am facing issue.There is no error .But still my Dialog flow can retrieve the Spreadsheet API values.

**Comment by sanchit892** [comment] 2020-03-11 04:53
Hey @jjoshua1995 can you please share your code and the error that you are getting while making the connection.

**Comment by jjoshua1995** [comment] 2020-03-11 05:02
[COde for json.txt](https://github.com/googleapis/nodejs-dialogflow/files/4316098/COde.for.json.txt)

Actually i don't have error but I am not getting body response from API .Also checked the logs in firebase but no response from API.

![Screenshot (106)](https://user-images.githubusercontent.com/59269996/76383903-b044c400-6333-11ea-9948-96558782fd2a.png)

**Comment by vishald123** [comment] 2020-03-11 05:45
@jjoshua1995, Please open a new issue for your issue.

**Comment by vishald123** [comment] 2020-03-12 18:46
@jjoshua1995, You are missing setting the **getdata()** intent. Set it the following way as you have set your welcome and fallback intent
``` js
intentMap.set('your intent name here. it should be same as from the DialogFlow console', getdata);
```

**Comment by jjoshua1995** [comment] 2020-03-15 03:29
Thanks ,  it didn't solve the issue .I have opened a new issue for the same @vishald123
